blogapp/urls.py
from django.urls import path
from .import views

app_name="blogapp"

urlpatterns = [
    path('hello/',views.homepage ,name="homepage"),
    path('contact/',views.contact,name="contact"),
    path('login/',views.login_user,name="login_user"),
    path('signup/',views.signup,name="signup"),
    path('logout/',views.logout_user,name="logout_user"),
    path('about/',views.about,name="about"),
 
    path('<id>/',views.single_post,name="single_post"),
    path('add_comment/<post_id>/',views.add_comment,name="add_comment"),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls')),
    path('',include('blogapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


 

blogapp/models.py
from email.policy import default
from django.db import models
from tinymce import models as tinymce_models

from django.contrib.auth.models import User

# Create your models here.
class PostModel(models.Model):
    post_title=models.CharField(max_length=50,null=False)
    post_summary=models.TextField()
    post_body=tinymce_models.HTMLField()
    post_image =models.ImageField(upload_to='post_images/', null=True)
    

    def __str__(self) -> str:
        return self.post_title

class Comment(models.Model):
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(PostModel,on_delete=models.CASCADE)
    comment_body=models.TextField()
    added_at=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.comment_body


class Contact(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    ph_no=models.CharField(max_length=50)
    text=models.TextField()


    def __str__(self) -> str:
        return self.name
    

  

        

blogapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import PostModel,Comment,Contact
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
def homepage(request):
    posts=PostModel.objects.all().order_by('-id')
    return render(request,'blogapp/homepage.html',{"posts":posts})
    


def single_post(request, id):
    post=PostModel.objects.get(id=id)
    comments=Comment.objects.filter(post=post).order_by('-id')
    context={
        'comments':comments,
        'post':post
        }
    return render(request,'blogapp/singlepage.html',context)

def contact(request):
    if request.method=="POST":
        name=request.POST.get('first_name')
        email=request.POST.get('email')
        ph_no=request.POST.get('phone')
        text=request.POST.get('comment')
        obj=Contact(name=name,email=email,ph_no=ph_no,text=text)
        obj.save()
    return render(request,'blogapp/contact.html')
  
@login_required
@require_http_methods(["POST"])
def add_comment(request,post_id):
    post_obj=PostModel.objects.get(id=post_id)
    comment_obj=Comment(post=post_obj,owner=request.user,comment_body=request.POST["msg"])
    comment_obj.save()
    return HttpResponseRedirect(reverse("blogapp:single_post",args=(post_id,)))

@require_http_methods(["POST","GET"])
def login_user(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        if not username or not password:
            return render(request,'blogapp/login.html',{"msg":"Both user name & password require to login"})
        else:
            user=authenticate(username=username,password=password)
            if user:
                login(request,user)
                return HttpResponseRedirect(reverse("blogapp:homepage"))
            else:
                return render(request,'blogapp/login.html',{"msg":"Invalid user & password"})
        
    elif request.method=="GET":
        msg=request.GET.get("msg")
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('blogapp:homepage'))
        return render(request,'blogapp/login.html',{"msg":msg})

        
@require_http_methods(["GET","POST"])
def signup(request):
    if request.method=="POST":
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        password_confrim=request.POST.get('password_confrim')
        if not username or not email or not password or not password_confrim:
            return render(request,'blogapp/signup.html',{"msg":"All fields are mandotary"})
        elif password!=password_confrim:
            return render(request,'blogapp/signup.html',{"msg":"Password & confrom password is not matching"})
        elif User.objects.filter(username=username).exists():
            return render(request,'blogapp/signup.html',{"msg":"Username already exists,Please use different user name."})
        elif User.objects.filter(email=email).exists():
            return render(request,'blogapp/signup.html',{"msg":"Email already exists,Please use different user Email."})  
        else:
            user=User.objects.create_user(username,email,password)
            return HttpResponseRedirect(reverse("blogapp:login_user") + "?msg=User created Succesfully. Please login")
    else:
        return render(request,'blogapp/signup.html',{})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("blogapp:login_user"))


def about(request):
    return render(request,'blogapp/about.html')

blogapp/templates/blogapp/about.html
{% load static %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="{% static 'blogapp/css/about.css' %}" rel="stylesheet" >
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
          <li ><a href="{% url 'blogapp:homepage' %}">Home</a></li>
      
        
          
        <li><a href="{% url 'blogapp:contact' %}">Contact Us</a></li>
       
        
       
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
      </div><!-- /.container-collapse -->
  </nav>
<div class="image-aboutus-banner"style="margin-top:70px">
   <div class="container">
    <div class="row">
        <div class="col-md-12">
         <h1 class="lg-text">About Us</h1>
         <p class="image-aboutus-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
       </div>
    </div>
</div>
</div>
<div class="bread-bar">
    	<div class="container">
        	<div class="row">
            	<div class="col-md-8 col-sm-6 col-xs-8">
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">About Us</li>
                    </ol>
            	</div>
                <div class="col-md-4 col-sm-6 col-xs-4">
                </div>
            </div>
      	</div>
    </div>
<div class="aboutus-secktion paddingTB60">
    <div class="container">
        <div class="row">
                	<div class="col-md-6">
                    	<h1 class="strong">Who we are and<br>what we do</h1>
                        <p class="lead">This is the world's leading portal for<br>easy and quick </p>
                    </div>
                    <div class="col-md-6">
                    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis egestas rhoncus. Donec facilisis fermentum sem, ac viverra ante luctus vel. Donec vel mauris quam.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis egestas rhoncus. Donec facilisis fermentum sem, ac viverra ante luctus vel. Donec vel mauris quam. Lorem ipsum dolor sit amet. Nulla convallis egestas rhoncus.</p>
                    </div>
</div>
    </div>
</div>
<div class="container team-sektion paddingTB60">
	<div class="row">
		<div class="site-heading text-center">
						<h3>Our Team</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt <br> ut labore et dolore magna aliqua. Ut enim ad minim </p>
						<div class="border"></div>
					</div>
	</div>
	<div class="row">
		<div class="col-md-4 team-box">
		    <div class="team-img thumbnail">
		        <img src="{% static 'blogapp/img/about-bg.jpg' %}">
		    <div class="team-content">    
		        <h3>Ready to take a Shot</h3>
		        <div class="border-team"></div>
		        <p>Lorem ipsum dolor sit amet, consectetur adipiscitas iverra ante luctus vel. Donec vel mauris quam.</p>
		        <div class="social-icons"> 
               <a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
	        </div>
		    </div>
		</div>
	</div>
	    <div class="col-md-4 team-box">
		    <div class="team-img thumbnail">
		        <img src="{% static 'blogapp/img/download.jfif' %}">
		    <div class="team-content">    
		        <h3>Goldy Blogger</h3>
		        <div class="border-team"></div>
		        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis egestas rhoncus. Donec facilisis fermentum sem, ac viverra ante luctus vel. Donec vel mauris quam.</p>
		        <div class="social-icons"> 
               <a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
	        </div>
		    </div>
		</div>
	</div>
	    <div class="col-md-4 team-box">
		    <div class="team-img thumbnail">
		        <img src="{% static 'blogapp/img/what-is-a-blog.jpg' %}">
		    <div class="team-content">    
		        <h3>Robert D'costa</h3>
		        <div class="border-team"></div>
		        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis egestas rhoncus. Donec facilisis fermentum sem, ac viverra ante luctus vel. Donec vel mauris quam.</p>
		        <div class="social-icons"> 
               <a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
	        </div>
		    </div>
		</div>
	</div>
	    
</div>
</div>
<div class="cta-sektion cta-padding35">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-9 col-xs-12">
                <h3><span class="glyphicon glyphicon-cog "></span> <b>Homes for sale?</b> Explore properties like a pro.</h3>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 Tpadding10">
                <button type="button" class="btn btn-primary site-btn">Start Right Now</button>
            </div>
        </div>
    </div>
</div>
<div class="footer-section">
    <div class="footer">
	<div class="container">
		<div class="col-md-4 footer-one">
			<h5>About Us </h5>
		    <p>Cras sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
		    	<div class="social-icons"> 
               <a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
	        </div>	
		</div>
		<div class="col-md-3 footer-two">
		    <h5>Information </h5>
		    <ul>
									<li><a href="maintenance.html">Maintenance Tips</a></li>
									<li><a href="contact.html">Locations</a></li>
									<li><a href="about.html">Testimonials</a></li>
									<li><a href="about.html">Careers</a></li>
									<li><a href="about.html">Partners</a></li>
								</ul>
		</div>
		<div class="col-md-3 footer-three">
		    <h5>Helpful Links </h5>
		    <ul>
									<li><a href="maintenance.html">Maintenance Tips</a></li>
									<li><a href="contact.html">Locations</a></li>
									<li><a href="about.html">Testimonials</a></li>
									<li><a href="about.html">Careers</a></li>
									<li><a href="about.html">Partners</a></li>
								</ul>
		</div>
		<div class="col-md-2 footer-four">
		    <h5>Helpful Links </h5>
		    <ul>
									<li><a href="maintenance.html">Maintenance Tips</a></li>
									<li><a href="contact.html">Locations</a></li>
									<li><a href="about.html">Testimonials</a></li>
									<li><a href="about.html">Careers</a></li>
									<li><a href="about.html">Partners</a></li>
								</ul>
		</div>
		
		<div class="clearfix"></div>
	</div>
</div>
    <div class="footer-bottom">
        <div class="container">
					<div class="row">
						<div class="col-sm-12 text-center ">
							<div class="copyright-text">
								<p>CopyRight © 2017 Digital All Rights Reserved</p>
							</div>
						</div> <!-- End Col -->
						
					</div>
				</div>
    </div>
</div>  

blogapp/templates/blogapp/blogcard.html
<div class="post-preview">
    <a href="{% url 'blogapp:single_post' post.id %}">
        <h2 class="post-title">{{post.post_title}}</h2>
        <h3 class="post-subtitle">{{post.post_summary}}</h3>
    </a>
    <p class="post-meta">
        Posted by
        <a href="#!">Admin</a>
        on September 24, 2022
    </p>
</div>

blogapp/templates/blogapp/contact.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="{% static 'blogapp/css/contact.css' %}" rel="stylesheet" >
<!------ Include the above in your HEAD tag ---------->

 
 <div class="container-fluid">
                <div class="row-fluid" >
                   
                      
                     <div class="col-md-offset-4 col-md-4" id="box">
                        <a href="{% url 'blogapp:homepage' %}"> <h5 class="Home" style="color: Gold; text-align:right;"> Home</h5></a>
						<h2 style="color: white;" >Contact Us!</h2> 
                           
                       
                            <hr>
                           

                                <form class="form-horizontal" action="{% url 'blogapp:contact' %}" method="POST" id="contact_form">
									{% csrf_token %}
                                    <fieldset>
                                        <!-- Form Name -->


                                        <!-- Text input-->

                                        <div class="form-group">

                                            <div class="col-md-12">
                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                                    <input name="first_name" placeholder="Name" class="form-control" type="text">
                                                </div>
                                            </div>
                                        </div>


                                  
                                        <!-- Text input-->
                                        <div class="form-group">

                                            <div class="col-md-12">
                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                                    <input name="email" placeholder="E-Mail Address" class="form-control" type="text">
                                                </div>
                                            </div>
                                        </div>


                                        <!-- Text input-->

                                        <div class="form-group">

                                            <div class="col-md-12">
                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                                                    <input name="phone" placeholder="(005)501-120101" class="form-control" type="text">
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Text input-->

                                        <div class="form-group">

                                            <div class="col-md-12 inputGroupContainer">
                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                                    <textarea class="form-control" name="comment" placeholder="Message"></textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">

                                            <div class="col-md-12">
                                                <button type="submit" class="btn btn-warning pull-right">Send<span class="glyphicon glyphicon-send"></span></button>
                                            </div>
                                        </div>

                                    </fieldset>
                                </form>
                    </div> 
</div>

blogapp/templates/blogapp/login.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="{% static 'blogapp/css/login.css' %}" rel="stylesheet" >
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Login in</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				{% if msg %}
                <p class="text-danger">{{msg}}</p>
				{% endif %}
				<form method="POST"  action="">
                    {% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input name=username type="text" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input name=password type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="{% url 'blogapp:signup' %}">Sign Up</a>
				</div>
				
			</div>
		</div>
	</div>
</div>
</body>
</html>

blogapp/templates/blogapp/single_comment.html
<div class="comment mt-4 text-justify">              
    <h4>{{comment_data.owner}}</h4>
    <span>-{{comment_data.added_at}}</span>
    <br>
    <p>{{comment_data.comment_body}}</p>
</div>

blogapp/templates/blogapp/singlepage.html
{% extends 'blogapp/structure.html' %}

{% block header_title %}{{post.post_title}}-Aliens blog{% endblock header_title %}


{% block 'main_heading' %}{{post.post_title}}

{% endblock 'main_heading' %}

{% block 'subheading' %}{{post.post_summary}}

{% endblock 'subheading' %}

{% block image %}{{post.post_image.url}}{% endblock image %}


{% block main_content %}{{post.post_body|safe}}{% endblock main_content %}

{% block comment %}


<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-5 col-md-6 col-12 pb-4">
                <h1>Comments</h1>
               
                 {% for comment in comments %}
                    {% include 'blogapp/single_comment.html' with comment_data=comment %}
                 {% endfor %}

            </div>
            <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
                
                {% if user.is_authenticated %}
                <form id="algin-form" method="post" action="{% url 'blogapp:add_comment' post.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <h4>Leave a comment</h4>
                        <label for="message">Message</label>
                        <textarea name="msg" id=""msg cols="30" rows="5" class="form-control" style="background-color: black; color: white;"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="fullname" class="form-control" disabled value="{{user.get_username}}">
                    </div>
                    <div class="form-group">
                        <button type="submit" id="post" class="btn">Post Comment</button>
                    </div>
                </form>
                {% else %}
                <h1 style="color: black;">Please<a class="text-warning" href="{% url 'blogapp:login_user' %}"> Login </a> to post a comment</h1>
                {% endif %}

            </div>
        </div>
    </div>
</section>

{% endblock comment %}

blogapp/templates/blogapp/structure.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block header_title %}{% endblock header_title %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blogapp/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blogapp/css/custom.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blogapp:homepage' %}">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:homepage' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:about' %}">About</a></li>
                  
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:contact' %}">Contact</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:logout_user' %}">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:login_user' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% block image %}{% endblock image %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1> {% block 'main_heading' %}{% endblock 'main_heading' %} </h1>
                            <span class="subheading"> {% block 'subheading' %}{% endblock 'subheading' %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% block main_content %}{% endblock main_content %}
                    </div>
             </div>
        </div>
                    
                    <!--Comment Secton-->
                    
                    {% block comment %}{% endblock comment %}
                    
                    <!--All Comment Secton-->
                
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blogapp/js/scripts.js' %}"</script>
    </body>
</html>